### ISSUE TITLE
Issue installing requirements or upgrading to Lightning 2

### ISSUE THREAD

**Issue by philpatton** [knshnb/kaggle-happywhale-1st-place#1]
Good afternoon!

I have been trying to recreate the winning score using the code in the README. I've done this easily in the past (like a year ago), but having been struggling to do so lately. I think a lot of these could be fixed by switching to Lightning 2.0, but have been struggling to make that work. Any ideas? 

## Running using current version

I believe the issue stems with the package versions in the `requirements.txt`. I am able to install the requirements, after tweaking the required version of Optuna. Then, running the `src.train` script prompts the following error: 
```
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
```
[Stack Exchange](https://stackoverflow.com/questions/72441758/typeerror-descriptors-cannot-not-be-created-directly) recommended running the following command `pip install protobuf==3.20.*`, which ran without issue.

Then, running the `src.train` file produces the following error: `AttributeError: 'WhaleDataModule' object has no attribute '_has_setup_TrainerFn.FITTING'` The [only thread](https://discourse.scverse.org/t/attributeerror-datasplitter-object-has-no-attribute-has-setup-trainerfn-fitting/1518) that I've seen discuss this recommended upgrading to `lightning v.2.0`.

## Running with Lightning 2.0

I've also tried upgrading to lightning 2.0, but that has some issues. Namely, `test_epoch_end()` has been deprecated. I've tried switching to `on_test_epoch_end()` (see proposed switch below). But this switch produces `np.nan` in the `pred_logit` and `embed_features` keys in the results dict.

Do you have any ideas on a better way to upgrade to 2.0?

Thanks! 
Phil

```
class SphereClassifier(LightningModule):
    def __init__(self, cfg: dict, id_class_nums=None, species_class_nums=None):
        super().__init__()
        ...
        self.test_step_outputs = []

    def test_step(self, batch, batch_idx):
        x = batch["image"]
        feat1 = self.get_feat(x)
        out1, out_species1 = self.head_id(feat1), self.head_species(feat1)
        feat2 = self.get_feat(x.flip(3))
        out2, out_species2 = self.head_id(feat2), self.head_species(feat2)
        pred_logit, pred_idx = ((out1 + out2) / 2).cpu().sort(descending=True)
        results_dict = {
            "original_index": batch["original_index"],
            "label": batch["label"],
            "label_species": batch["label_species"],
            "pred_logit": pred_logit[:, :1000],
            "pred_idx": pred_idx[:, :1000],
            "pred_species": ((out_species1 + out_species2) / 2).cpu(),
            "embed_features1": feat1.cpu(),
            "embed_features2": feat2.cpu(),
        }
        self.test_step_outputs.append(results_dict)
        return results_dict

    def on_test_epoch_end(self):
        outputs = self.test_step_outputs
        if self.trainer.global_rank == 0:
            epoch_results: Dict[str, np.ndarray] = {}
            for key in outputs[0].keys():
                if torch.cuda.device_count() > 1:
                    result = torch.cat([x[key] for x in outputs], dim=1).flatten(end_dim=1)
                else:
                    result = torch.cat([x[key] for x in outputs], dim=0)
                epoch_results[key] = result.detach().cpu().numpy()
            np.savez_compressed(self.test_results_fp, **epoch_results)

```

**Comment by knshnb** [comment]
Thanks for raising an issue! Let me investigate it this weekend.

**Comment by philpatton** [comment]
Sounds great. Thank you!

**Comment by knshnb** [comment]
I'm sorry for the late reply.
I could not reproduce your error probably due to different versions of the libraries. I added some dependencies by https://github.com/knshnb/kaggle-happywhale-1st-place/commit/508e8abca01ac0315f1ec1ee4ad7ff823431975b so that execution on Docker should work currently. Could you try using Docker by the following procedure?
1: Build a Docker image
```
docker build -t happywhale .
```
2: Run interactive shell
```
docker run --rm -it -v .:/workspace happywhale /bin/bash
```

**Comment by philpatton** [comment]
No worries! Thank you again for tackling this. I've tried your solution via Docker on my laptop, which works great.

Unfortunately, I'm unable to install Docker on our university's computing cluster for security reasons (and, of course, my laptop's GPU leaves much to be desired). As such, I'm left with installing the repo/requirements in a conda environment via pip, which sadly still breaks the script. Do you think there's a band-aid solution for users in my situation? Perhaps it has to do with the PyTorch version? Apologies for my ignorance!!!

**Comment by knshnb** [comment]
Ummm, could you probably compare the module versions, especially PyTorch, in the local Docker and the computing cluster? You might be able to run the script by matching the conda/pip's environment to Docker's.
